#!/usr/bin/env python3
"""Regenerate missing publication figures from already exported CSV results.

This script does not invent missing numerical arrays. Figure 03 requires either
``channel_sweep.csv`` from the patched full run or per-span channel CSV files.
Constellation figures require recovered symbol samples and are therefore created
by rerunning the patched publication pipeline rather than from summary metrics.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import numpy as np
import pandas as pd

from isrs_scl.visualization.publication_plots import (
    plot_gsnr_distance_heatmap,
    plot_launch_profiles,
    plot_waveform_metrics_comparison,
    plot_waveform_power_consistency,
)


def _load_channel_sweep(results_dir: Path) -> pd.DataFrame | None:
    combined = results_dir / "channel_sweep.csv"
    if combined.exists():
        return pd.read_csv(combined)

    frames: list[pd.DataFrame] = []
    pattern = re.compile(r"(?P<strategy>flat|fixed|adaptive)_(?P<spans>\d+)_spans\.csv")
    for path in sorted(results_dir.glob("*_spans.csv")):
        match = pattern.fullmatch(path.name)
        if match is None:
            continue
        frame = pd.read_csv(path)
        if "strategy" not in frame:
            frame.insert(0, "strategy", match.group("strategy").title())
        if "spans" not in frame:
            frame.insert(1, "spans", int(match.group("spans")))
        if "distance_km" not in frame:
            raise ValueError(f"{path} has no distance_km column")
        frames.append(frame)
    return pd.concat(frames, ignore_index=True) if frames else None


def _required_snr(results_dir: Path) -> float | None:
    calibration_path = results_dir / "b2b_calibration.csv"
    if not calibration_path.exists():
        return None
    calibration = pd.read_csv(calibration_path)
    if "input_snr_db" not in calibration or "ngmi" not in calibration:
        return None
    passing = calibration[calibration["ngmi"] >= 0.90]
    return float(passing.iloc[0]["input_snr_db"]) if not passing.empty else None


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", type=Path, default=Path("results/publication"))
    parser.add_argument("--figures", type=Path, default=Path("figures"))
    parser.add_argument("--dpi", type=int, default=600)
    parser.add_argument("--strategy", default="Adaptive")
    parser.add_argument("--consistency-tolerance-db", type=float, default=2.0)
    args = parser.parse_args()

    args.figures.mkdir(parents=True, exist_ok=True)
    generated: list[str] = []

    channel_sweep = _load_channel_sweep(args.results)
    if channel_sweep is not None:
        plot_gsnr_distance_heatmap(
            channel_sweep,
            args.strategy,
            args.figures / "03_gsnr_distance_heatmap",
            args.dpi,
            threshold_db=_required_snr(args.results),
        )
        generated.append("03_gsnr_distance_heatmap")
    else:
        print(
            "Skipped Figure 03: no channel_sweep.csv or per-span channel CSV files were found."
        )

    waveform_path = args.results / "waveform_metrics.csv"
    if waveform_path.exists():
        waveform = pd.read_csv(waveform_path)
        plot_waveform_metrics_comparison(
            waveform,
            args.figures / "07_evm_ber_ngmi_comparison",
            args.dpi,
            ber_target=0.004,
            ngmi_target=0.90,
        )
        plot_waveform_power_consistency(
            waveform,
            args.figures / "13_power_waveform_consistency",
            args.dpi,
            tolerance_db=args.consistency_tolerance_db,
        )
        generated.extend(
            ["07_evm_ber_ngmi_comparison", "13_power_waveform_consistency"]
        )
    else:
        print("Skipped Figures 07 and 13: waveform_metrics.csv was not found.")

    launch_path = args.results / "launch_profiles.csv"
    if launch_path.exists():
        plot_launch_profiles(
            pd.read_csv(launch_path),
            args.figures / "12_launch_profiles",
            args.dpi,
        )
        generated.append("12_launch_profiles")
    else:
        print("Skipped Figure 12: launch_profiles.csv was not found.")

    print("Generated:", ", ".join(generated) if generated else "nothing")
    print(
        "Figures 05, 06 and 06b require recovered symbol arrays and are generated by "
        "the patched full pipeline."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())